spring:
  application:
    name: tracker-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/NomedXD/TelegramTrackerConfig.git
          username: NomedXD
          password: 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
          default-label: main
          search-paths: tracker-accountant-service,tracker-bot,tracker-eureka-server,tracker-gateway-server,tracker-notificator-service,tracker-sender-service,tracker-team-service
          skip-ssl-validation: true
server:
  port: 24100